#!/usr/bin/env python3
import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
import paramiko
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('10.36.177.138', username='pm', password='11192655')
def run(c, t=10):
    si, so, se = ssh.exec_command(c, timeout=t)
    return so.read().decode(errors='replace').strip()
print('=== sat_proxy processo ===')
print(run('ps aux | grep sat_proxy | grep -v grep'))
print()
print('=== sat_proxy.log ===')
print(run('cat /tmp/sat_proxy.log 2>&1'))
print()
print('=== porta 8765 aberta? ===')
print(run('ss -tlnp | grep 8765'))
print()
print('=== restart sat_proxy ===')
print(run('pkill -f sat_proxy.py 2>/dev/null'))
import time; time.sleep(1)
print(run('nohup python3 /opt/convex-viaturas/sat_proxy.py > /tmp/sat_proxy.log 2>&1 & disown'))
time.sleep(2)
print(run('curl -s -m 5 http://localhost:8765/sat/consulta?re=111926 2>&1 | head -c 1000'))
print()
print('=== sat_proxy.log novo ===')
print(run('cat /tmp/sat_proxy.log'))
print()
print('=== Container chama host.docker.internal:8765 ===')
print(run('SUDO_ASKPASS=/opt/askpass-sudo.sh sudo -A docker exec auth-api-viaturas curl -s -m 10 http://host.docker.internal:8765/sat/consulta?re=111926 2>&1 | head -c 500'))
ssh.close()
